# Generated by Django 4.1.3 on 2024-04-08 13:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_remove_notes_shared_with_shared'),
    ]

    operations = [
        migrations.AddField(
            model_name='folders',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folders',
            name='edit_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
