# Generated by Django 4.1.3 on 2024-04-09 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_folders_note_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folders',
            name='note_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notes.notes'),
        ),
    ]
