# Generated by Django 4.1.3 on 2024-04-09 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_alter_folders_note_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folders',
            name='note_name',
        ),
        migrations.CreateModel(
            name='FolderNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.folders')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
