# Generated by Django 5.2.1 on 2025-05-23 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_shared_shared_by_alter_shared_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared',
            name='shared_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
