# Generated by Django 5.2.1 on 2025-06-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0010_shared_shared_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='shared',
            name='permission',
            field=models.CharField(choices=[('view', 'View'), ('edit', 'Edit')], default='view', max_length=10),
        ),
    ]
