# Generated by Django 5.2.1 on 2025-08-01 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_shared_permission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='shared',
            unique_together={('note', 'shared_with')},
        ),
    ]
