# Generated by Django 5.2.1 on 2025-08-11 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_alter_shared_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
